### ISSUE TITLE
Error on build -- * is not an export variable

### ISSUE THREAD

**Issue by eamodio** [vincentdchan/webpack-deep-scope-analysis-plugin#4]
Hi, I was trying this out on my OSS [GitLens](https://github.com/eamodio/vscode-gitlens/) project and am getting the following error. I'm not sure what file/import/export is causing this. Any ideas?

```
C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-deep-scope-analysis\lib\analyser\moduleAnalyser.js:145
                throw new Error(`${usedExport} is not an export variable`);
                ^

Error: Commands is not an export variable
    at ModuleAnalyser.generateExportInfo (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-deep-scope-analysis\lib\analyser\moduleAnalyser.js:145:23)
    at compilation.hooks.dependencyReference.tap (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack-deep-scope-plugin\index.js:34:56)
    at SyncWaterfallHook.eval [as call] (eval at create (C:\Users\Eric\code\vscode-gitlens\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:16)
    at Compilation.getDependencyReference (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\Compilation.js:1474:41)
    at processDependency (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:80:37)
    at processDependenciesBlock (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:67:8)
    at compilation.hooks.optimizeDependencies.tap.modules (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:109:7)
    at SyncBailHook.eval [as call] (eval at create (C:\Users\Eric\code\vscode-gitlens\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:13:16)
    at SyncBailHook.lazyCompileHook [as _call] (C:\Users\Eric\code\vscode-gitlens\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\Compilation.js:1162:36)
    at hooks.make.callAsync.err (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\Compiler.js:547:17)
    at _err0 (eval at create (C:\Users\Eric\code\vscode-gitlens\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\Compilation.js:1064:12)
    at processModuleDependencies.err (C:\Users\Eric\code\vscode-gitlens\node_modules\webpack\lib\Compilation.js:980:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by vincentdchan** [comment]
The error is saying that the analyzer can not find `Command` in the export map of that module, can you provide the file content?

**Comment by vincentdchan** [comment]
I found that you exported `Commands` in [common.ts](https://raw.githubusercontent.com/eamodio/vscode-gitlens/master/src/commands/common.ts). I guess TypeScript transpiled your code into the ES5 syntaxes, which this plugin cannot analyze.

You may need to check the config of TypeScript, the analysis is based on the ES6 syntaxes.

**Comment by eamodio** [comment]
Hrm, I'm targeting `esnext` for modules: https://github.com/eamodio/vscode-gitlens/blob/develop/tsconfig.json#L6

**Comment by vincentdchan** [comment]
Great, can you take a look at the TypeScript output of that file? It would help. Or I will compile and watch it tomorrow, maybe

**Comment by eamodio** [comment]
I tried changing it to `es2105` after just removing all my dynamic imports, but I get the same issue. I'm not sure how to really see the typescript output as this is all running through the webpack pipeline via `ts-loader`

**Comment by eamodio** [comment]
If I compile it with `tsc`, I get:
```js
...
export var Commands;
(function (Commands) {
    Commands["ClearFileAnnotations"] = "gitlens.clearFileAnnotations";
    Commands["CloseUnchangedFiles"] = "gitlens.closeUnchangedFiles";
    Commands["ComputingFileAnnotations"] = "gitlens.computingFileAnnotations";
    Commands["CopyMessageToClipboard"] = "gitlens.copyMessageToClipboard";
    Commands["CopyRemoteFileUrlToClipboard"] = "gitlens.copyRemoteFileUrlToClipboard";
    Commands["CopyShaToClipboard"] = "gitlens.copyShaToClipboard";
    Commands["DiffDirectory"] = "gitlens.diffDirectory";
    Commands["DiffHeadWithBranch"] = "gitlens.diffHeadWithBranch";
    Commands["DiffWorkingWithBranch"] = "gitlens.diffWorkingWithBranch";
    Commands["ExternalDiffAll"] = "gitlens.externalDiffAll";
    Commands["DiffWith"] = "gitlens.diffWith";
    Commands["DiffWithBranch"] = "gitlens.diffWithBranch";
    Commands["DiffWithNext"] = "gitlens.diffWithNext";
    Commands["DiffWithPrevious"] = "gitlens.diffWithPrevious";
    Commands["DiffWithPreviousInDiff"] = "gitlens.diffWithPreviousInDiff";
    Commands["DiffLineWithPrevious"] = "gitlens.diffLineWithPrevious";
    Commands["DiffWithRevision"] = "gitlens.diffWithRevision";
    Commands["DiffWithWorking"] = "gitlens.diffWithWorking";
    Commands["DiffLineWithWorking"] = "gitlens.diffLineWithWorking";
    Commands["ExternalDiff"] = "gitlens.externalDiff";
    Commands["ExplorersOpenDirectoryDiff"] = "gitlens.explorers.openDirectoryDiff";
    Commands["ExplorersOpenDirectoryDiffWithWorking"] = "gitlens.explorers.openDirectoryDiffWithWorking";
    Commands["OpenChangedFiles"] = "gitlens.openChangedFiles";
    Commands["OpenBranchesInRemote"] = "gitlens.openBranchesInRemote";
    Commands["OpenBranchInRemote"] = "gitlens.openBranchInRemote";
    Commands["OpenCommitInRemote"] = "gitlens.openCommitInRemote";
    Commands["OpenFileInRemote"] = "gitlens.openFileInRemote";
    Commands["OpenFileRevision"] = "gitlens.openFileRevision";
    Commands["OpenInRemote"] = "gitlens.openInRemote";
    Commands["OpenRepoInRemote"] = "gitlens.openRepoInRemote";
    Commands["OpenWorkingFile"] = "gitlens.openWorkingFile";
    Commands["ResetSuppressedWarnings"] = "gitlens.resetSuppressedWarnings";
    Commands["ShowCommitSearch"] = "gitlens.showCommitSearch";
    Commands["ShowGitExplorer"] = "gitlens.showGitExplorer";
    Commands["ShowHistoryExplorer"] = "gitlens.showHistoryExplorer";
    Commands["ShowLastQuickPick"] = "gitlens.showLastQuickPick";
    Commands["ShowQuickCommitDetails"] = "gitlens.showQuickCommitDetails";
    Commands["ShowQuickCommitFileDetails"] = "gitlens.showQuickCommitFileDetails";
    Commands["ShowQuickFileHistory"] = "gitlens.showQuickFileHistory";
    Commands["ShowQuickBranchHistory"] = "gitlens.showQuickBranchHistory";
    Commands["ShowQuickCurrentBranchHistory"] = "gitlens.showQuickRepoHistory";
    Commands["ShowQuickRepoStatus"] = "gitlens.showQuickRepoStatus";
    Commands["ShowQuickStashList"] = "gitlens.showQuickStashList";
    Commands["ShowResultsExplorer"] = "gitlens.showResultsExplorer";
    Commands["ShowSettingsPage"] = "gitlens.showSettingsPage";
    Commands["ShowWelcomePage"] = "gitlens.showWelcomePage";
    Commands["StashApply"] = "gitlens.stashApply";
    Commands["StashDelete"] = "gitlens.stashDelete";
    Commands["StashSave"] = "gitlens.stashSave";
    Commands["SwitchMode"] = "gitlens.switchMode";
    Commands["ToggleCodeLens"] = "gitlens.toggleCodeLens";
    Commands["ToggleFileBlame"] = "gitlens.toggleFileBlame";
    Commands["ToggleFileHeatmap"] = "gitlens.toggleFileHeatmap";
    Commands["ToggleFileRecentChanges"] = "gitlens.toggleFileRecentChanges";
    Commands["ToggleLineBlame"] = "gitlens.toggleLineBlame";
    Commands["ToggleReviewMode"] = "gitlens.toggleReviewMode";
    Commands["ToggleZenMode"] = "gitlens.toggleZenMode";
})(Commands || (Commands = {}));
...
```

**Comment by vincentdchan** [comment]
Can't see any problems from the above output, I'll debug myself tomorrow.

**Comment by eamodio** [comment]
Thank you!

**Comment by vincentdchan** [comment]
Great, it's a bug that this plugin cannot resolve the variables which exported from another module. Will fix it as soon as possible.

**Comment by vincentdchan** [comment]
Updating to v1.4.1(sorry not 1.4.0) will fix your problem, but I found that it seems that this plugin can't reduce the size of the bundle. Maybe we can find some scenes to optimize.
